apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: identityhoprds.hoprnet.org
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundle: {{ .Values.hoprdOperator.webhook.tls.crt | b64enc | quote }}
        service:
          name: {{ .Values.hoprdOperator.webhook.service.name }}
          namespace: {{ .Release.Namespace }}
          path: /convert
          port: {{ .Values.hoprdOperator.webhook.service.port }}
      conversionReviewVersions:
        - v1
  group: hoprnet.org
  names:
    kind: IdentityHoprd
    plural: identityhoprds
    singular: identityhoprd
    shortNames:
      - identityhoprd
  scope: Namespaced
  versions:
    - name: v1alpha3
      served: true
      storage: true
      additionalPrinterColumns:
      - description: Identity phase
        jsonPath: .status.phase
        name: Phase
        type: string
      - description: Pool name
        jsonPath: .spec.identityPoolName
        name: Pool
        type: string
      - description: Hoprd Name
        jsonPath: .status.hoprdNodeName
        name: HoprdNode
        type: string
      - description: Creation timestamp
        jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
      schema:
        openAPIV3Schema:
          description: Schema definition for Identity Hoprd
          properties:
            spec:
              properties:
                identityFile:
                  description: Contents of the hoprd identity file
                  format: password
                  type: string
                identityPoolName:
                  description: Name of the Identity Pool
                  type: string
                moduleAddress:
                  description: Ethereum address of the module
                  type: string
                nodeAddress:
                  description: Ethereum native address of the Hoprd node
                  type: string
                safeAddress:
                  description: Ethereum address of the safe linked to the Hoprd node
                  type: string
              required:
              - identityPoolName
              - identityFile
              - nodeAddress
              - safeAddress
              - moduleAddress
              type: object
            status:
              description: The status object of IdentityHoprd node
              nullable: true
              properties:
                hoprdNodeName:
                  description: Name of the HoprdNode
                  type: string
                observedGeneration:
                  description: The current applied metadata.generation specification
                  type: number
                phase:
                  description: Phase of the last applied change
                  enum:
                  - Initialized
                  - Failed
                  - Ready
                  - InUse
                  - Deleting
                  type: string
              required:
              - observedGeneration
              - phase
              type: object
          required:
          - spec
          type: object
    - name: v1alpha2
      served: true
      storage: false
      additionalPrinterColumns:
      - description: Identity phase
        jsonPath: .status.phase
        name: Phase
        type: string
      - description: Pool name
        jsonPath: .spec.identityPoolName
        name: Pool
        type: string
      - description: Hoprd Name
        jsonPath: .status.hoprdNodeName
        name: HoprdNode
        type: string
      - description: Creation timestamp
        jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
      schema:
        openAPIV3Schema:
          description: Schema definition for Identity Hoprd
          properties:
            spec:
              properties:
                identityFile:
                  description: Contents of the hoprd identity file
                  format: password
                  type: string
                identityPoolName:
                  description: Name of the Identity Pool
                  type: string
                moduleAddress:
                  description: Ethereum address of the module
                  type: string
                nativeAddress:
                  description: Ethereum native address of the Hoprd node
                  type: string
                peerId:
                  description: PeerId of the Hoprd node
                  type: string
                safeAddress:
                  description: Ethereum address of the safe linked to the Hoprd node
                  type: string
              required:
              - identityPoolName
              - identityFile
              - peerId
              - nativeAddress
              - safeAddress
              - moduleAddress
              type: object
            status:
              description: The status object of IdentityHoprd node
              nullable: true
              properties:
                checksum:
                  description: Checksum of the last applied change
                  type: string
                hoprdNodeName:
                  description: Name of the HoprdNode
                  type: string
                phase:
                  description: Phase of the last applied change
                  enum:
                  - Initialized
                  - Failed
                  - Ready
                  - InUse
                  - Deleting
                  type: string
                updateTimestamp:
                  description: Timestamp of the last applied change
                  format: date-time
                  type: string
              required:
              - updateTimestamp
              - checksum
              - phase
              type: object
          required:
          - spec
          type: object
