apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: identitypools.hoprnet.org
spec:
  group: hoprnet.org
  names:
    kind: IdentityPool
    plural: identitypools
    singular: identitypool
    shortNames:
      - identitypool
  scope: Namespaced
  versions:
    - name: v1alpha3
      served: true
      storage: true
      additionalPrinterColumns:
      - description: Hoprd network name
        jsonPath: .spec.network
        name: Network
        type: string
      - description: Identity pool phase
        jsonPath: .status.phase
        name: Phase
        type: string
      - description: Identity size
        jsonPath: .status.size
        name: Size
        type: number
      - description: Identity locked
        jsonPath: .status.locked
        name: Locked
        type: number
      - description: Creation timestamp
        jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
      schema:
        openAPIV3Schema:
          description: Schema definition for Identity Hoprd
          properties:
            spec:
              properties:
                funding:
                  properties:
                    nativeAmount:
                      description: xDai limit amount (unit xDai)
                      type: string
                    schedule:
                      description: Cron schedule format
                      type: string
                  required:
                  - schedule
                  - nativeAmount
                  type: object
                network:
                  description: Name of the Hoprd network
                  type: string
                secretName:
                  description: Name of the secret containing sensitive data
                  type: string
              required:
              - network
              - secretName
              type: object
            status:
              description: The status object of IdentityHoprd node
              nullable: true
              properties:
                checksum:
                  description: Checksum of the last applied change
                  type: string
                locked:
                  description: Amount of locked identities
                  type: number
                phase:
                  description: Phase of the last applied change
                  enum:
                  - Initialized
                  - Failed
                  - OutOfSync
                  - Ready
                  - Deleting
                  type: string
                size:
                  description: Amount of identities created
                  type: number
                updateTimestamp:
                  description: Timestamp of the last applied change
                  format: date-time
                  type: string
              required:
              - updateTimestamp
              - checksum
              - phase
              - size
              - locked
              type: object
          required:
          - spec
          type: object
    - name: v1alpha2
      served: true
      storage: false
      additionalPrinterColumns:
      - description: Hoprd network name
        jsonPath: .spec.network
        name: Network
        type: string
      - description: Identity pool phase
        jsonPath: .status.phase
        name: Phase
        type: string
      - description: Identity size
        jsonPath: .status.size
        name: Size
        type: number
      - description: Identity locked
        jsonPath: .status.locked
        name: Locked
        type: number
      - description: Creation timestamp
        jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
      schema:
        openAPIV3Schema:
          description: Schema definition for Identity Hoprd
          properties:
            spec:
              properties:
                funding:
                  properties:
                    nativeAmount:
                      description: xDai limit amount (unit xDai)
                      type: string
                    schedule:
                      description: Cron schedule format
                      type: string
                  required:
                  - schedule
                  - nativeAmount
                  type: object
                network:
                  description: Name of the Hoprd network
                  type: string
                secretName:
                  description: Name of the secret containing sensitive data
                  type: string
              required:
              - network
              - secretName
              type: object
            status:
              description: The status object of IdentityHoprd node
              nullable: true
              properties:
                checksum:
                  description: Checksum of the last applied change
                  type: string
                locked:
                  description: Amount of locked identities
                  type: number
                phase:
                  description: Phase of the last applied change
                  enum:
                  - Initialized
                  - Failed
                  - OutOfSync
                  - Ready
                  - Deleting
                  type: string
                size:
                  description: Amount of identities created
                  type: number
                updateTimestamp:
                  description: Timestamp of the last applied change
                  format: date-time
                  type: string
              required:
              - updateTimestamp
              - checksum
              - phase
              - size
              - locked
              type: object
          required:
          - spec
          type: object
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: {{ .Values.hoprdOperator.webhook.serviceName }}
          namespace: {{ .Release.Namespace }}
          path: /convert
        caBundle: {{ .Values.hoprdOperator.webhook.tls.crt | b64enc | quote }}
      conversionReviewVersions:
        - v1
