apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: identitypools.hoprnet.org
  namespace: {{ .Release.Namespace | quote }}
spec:
  group: hoprnet.org
  names:
    kind: IdentityPool
    plural: identitypools
    singular: identitypool
    shortNames:
      - identitypool
  scope: Namespaced
  versions:
    - name: v1alpha3
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Network
          type: string
          description: Hoprd network name
          jsonPath: .spec.network
        - name: Phase
          type: string
          description: Identity pool phase
          jsonPath: .status.phase
        - name: Size
          type: number
          description: Identity size
          jsonPath: .status.size
        - name: Locked
          type: number
          description: Identity locked
          jsonPath: .status.locked
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          description: Schema definition for Identity Hoprd
          type: object
          properties:
            spec:
              type: object
              properties:
                network:
                  type: string
                  description: 'Name of the Hoprd network'
                secretName:
                  type: string
                  description: Name of the secret containing sensitive data
                funding:
                  type: object
                  properties:
                    schedule:
                      type: string
                      description: 'Cron schedule format'
                    nativeAmount:
                      type: string
                      description: 'xDai limit amount (unit xDai)'
                  required:
                    - schedule
                    - nativeAmount
              required:
                - network
                - secretName
            status:
              description: The status object of IdentityHoprd node
              nullable: true
              properties:
                updateTimestamp:
                  format: date-time
                  type: string
                  description: Timestamp of the last applied change
                checksum:
                  type: string
                  description: Checksum of the last applied change
                phase:
                  description: Phase of the last applied change
                  type: string
                  enum:
                  - Initialized
                  - Failed
                  - OutOfSync
                  - Ready
                  - Deleting
                size:
                  description: Amount of identities created
                  type: number
                locked:
                  description: Amount of locked identities
                  type: number
              required: [ "updateTimestamp", "checksum", "phase", "size", "locked"]
              type: object
          required:
          - spec
    - name: v1alpha2
      additionalPrinterColumns:
      - description: Hoprd network name
        jsonPath: .spec.network
        name: Network
        type: string
      - description: Identity pool phase
        jsonPath: .status.phase
        name: Phase
        type: string
      - description: Identity size
        jsonPath: .status.size
        name: Size
        type: number
      - description: Identity locked
        jsonPath: .status.locked
        name: Locked
        type: number
      - jsonPath: .metadata.creationTimestamp
        name: Age
        type: date

      schema:
        openAPIV3Schema:
          description: Schema definition for Identity Hoprd
          properties:
            spec:
              properties:
                funding:
                  properties:
                    nativeAmount:
                      description: xDai limit amount (unit xDai)
                      type: string
                    schedule:
                      description: Cron schedule format
                      type: string
                  required:
                  - schedule
                  - nativeAmount
                  type: object
                network:
                  description: Name of the Hoprd network
                  type: string
                secretName:
                  description: Name of the secret containing sensitive data
                  type: string
              required:
              - network
              - secretName
              type: object
            status:
              description: The status object of IdentityHoprd node
              nullable: true
              properties:
                checksum:
                  description: Checksum of the last applied change
                  type: string
                locked:
                  description: Amount of locked identities
                  type: number
                phase:
                  description: Phase of the last applied change
                  enum:
                  - Initialized
                  - Failed
                  - OutOfSync
                  - Ready
                  - Deleting
                  type: string
                size:
                  description: Amount of identities created
                  type: number
                updateTimestamp:
                  description: Timestamp of the last applied change
                  format: date-time
                  type: string
              required:
              - updateTimestamp
              - checksum
              - phase
              - size
              - locked
              type: object
          required:
          - spec
          type: object