apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: identityhoprds.hoprnet.org
  namespace: {{ .Release.Namespace | quote }}
spec:
  group: hoprnet.org
  names:
    kind: IdentityHoprd
    plural: identityhoprds
    singular: identityhoprd
    shortNames:
      - identityhoprd
  scope: Namespaced
  versions:
    - name: v1alpha3
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Phase
          type: string
          description: Identity phase
          jsonPath: .status.phase
        - name: Pool
          type: string
          description: Pool name
          jsonPath: .spec.identityPoolName
        - name: HoprdNode
          type: string
          description: Hoprd Name
          jsonPath: .status.hoprdNodeName
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          description: Schema definition for Identity Hoprd
          type: object
          properties:
            spec:
              type: object
              properties:
                identityPoolName:
                  type: string
                  description: 'Name of the Identity Pool'
                identityFile:
                  type: string
                  format: password
                  description: 'Contents of the hoprd identity file'
                nodeAddress:
                  type: string
                  description: 'Ethereum native address of the Hoprd node'
                safeAddress:
                  type: string
                  description: 'Ethereum address of the safe linked to the Hoprd node'
                moduleAddress:
                  type: string
                  description: 'Ethereum address of the module'
              required:
                - identityPoolName
                - identityFile
                - nodeAddress
                - safeAddress
                - moduleAddress
            status:
              description: The status object of IdentityHoprd node
              nullable: true
              properties:
                updateTimestamp:
                  format: date-time
                  type: string
                  description: Timestamp of the last applied change
                checksum:
                  type: string
                  description: Checksum of the last applied change
                phase:
                  description: Phase of the last applied change
                  type: string
                  enum:
                  - Initialized
                  - Failed
                  - Ready
                  - InUse
                  - Deleting
                hoprdNodeName:
                  type: string
                  description: Name of the HoprdNode
              required: [ "updateTimestamp", "checksum", "phase"]
              type: object
          required:
          - spec
    - name: v1alpha2
      additionalPrinterColumns:
      - description: Identity phase
        jsonPath: .status.phase
        name: Phase
        type: string
      - description: Pool name
        jsonPath: .spec.identityPoolName
        name: Pool
        type: string
      - description: Hoprd Name
        jsonPath: .status.hoprdNodeName
        name: HoprdNode
        type: string
      - jsonPath: .metadata.creationTimestamp
        name: Age
        type: date
      schema:
        openAPIV3Schema:
          description: Schema definition for Identity Hoprd
          properties:
            spec:
              properties:
                identityFile:
                  description: Contents of the hoprd identity file
                  format: password
                  type: string
                identityPoolName:
                  description: Name of the Identity Pool
                  type: string
                moduleAddress:
                  description: Ethereum address of the module
                  type: string
                nativeAddress:
                  description: Ethereum native address of the Hoprd node
                  type: string
                peerId:
                  description: PeerId of the Hoprd node
                  type: string
                safeAddress:
                  description: Ethereum address of the safe linked to the Hoprd node
                  type: string
              required:
              - identityPoolName
              - identityFile
              - peerId
              - nativeAddress
              - safeAddress
              - moduleAddress
              type: object
            status:
              description: The status object of IdentityHoprd node
              nullable: true
              properties:
                checksum:
                  description: Checksum of the last applied change
                  type: string
                hoprdNodeName:
                  description: Name of the HoprdNode
                  type: string
                phase:
                  description: Phase of the last applied change
                  enum:
                  - Initialized
                  - Failed
                  - Ready
                  - InUse
                  - Deleting
                  type: string
                updateTimestamp:
                  description: Timestamp of the last applied change
                  format: date-time
                  type: string
              required:
              - updateTimestamp
              - checksum
              - phase
              type: object
          required:
          - spec
          type: object