hoprdOperator:
  webhook:
    service:
      ## @param hoprdOperator.webhook.service.name Name of the webhook service
      ##
      name: ""
      ## @param hoprdOperator.webhook.service.port Port of the webhook service
      ##
      port: 8443
    tls:
      ## @param hoprdOperator.webhook.tls.crt TLS certificate for the webhook server
      ##
      crt: ""