{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hoprd-operator.fullname" . }}-webhook-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "A valid tls.crt is required!" .Values.webhook.tls.crt | b64enc | quote }}
  tls.key: {{ required "A valid tls.key is required!" .Values.webhook.tls.key | b64enc | quote }}
{{- end }}