{{- if .Values.hoprdOperator.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hoprd-operator.fullname" . }}-webhook
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "hoprd-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: 8443
      name: webhook
      targetPort: webhook
  selector:
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: {{ include "hoprd-operator.name" . }}
      app.kubernetes.io/name: {{ .Release.Name }}
{{- end }}