---

name: 'Publish Helm chart CRDs'

on:
  push:
    branches:
      - master
    paths:
      - "charts/hoprd-crds/**"
concurrency:
  group: ${{ github.head_ref }}-crds-publish
  cancel-in-progress: false
jobs:
  publish:
    runs-on: self-hosted-hoprnet-small

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Helm chart version
        id: get_version
        run: |
          HELM_CHART_VERSION=$(grep '^version:' Chart.yaml | sed 's/.*: //')
          echo "HELM_CHART_VERSION=${HELM_CHART_VERSION}" >> $GITHUB_OUTPUT
        working-directory: 'charts/hoprd-crds/'

      - name: Setup GCP
        id: gcp
        uses: hoprnet/hopr-workflows/actions/setup-gcp@12c56020e16036982e6cc529848edeedfc705865 # master
        with:
          google-credentials: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
          login-artifact-registry: 'true'

      - name: Helm Package
        run: |
          helm package . --version ${{ steps.get_version.outputs.HELM_CHART_VERSION }}
        working-directory: 'charts/hoprd-crds/'

      - name: Helm Publish
        run: |
          helm push hoprd-crds-${{ steps.get_version.outputs.HELM_CHART_VERSION }}.tgz oci://europe-west3-docker.pkg.dev/hoprassociation/helm-charts
        working-directory: 'charts/hoprd-crds/'

      - name: Tag Helm version
        run: |
            git config user.email "noreply@hoprnet.org"
            git config user.name "HOPR CI robot"
            git tag helm-hoprd-crds-${{ steps.get_version.outputs.HELM_CHART_VERSION }}
            git push origin helm-hoprd-crds-${{ steps.get_version.outputs.HELM_CHART_VERSION }}
